[package]
name = "compiler-in-rust"
version = "0.1.0"
authors = ["Leon Behrndt <leonbehrndt1@gmail.com>"]
edition = "2021"
# Optional metadata
license = "MIT"
repository = "https://github.com/lbehrndt/compiler-in-rust"
